version: "2.2"
services:
  my-postgres:
    image: postgres
    ports:
      - "9000:5432"
    environment:
      # this setup will also represent in ./config/config.json
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a455328fm
      POSTGRES_DB: assignment
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql