version: "2.2"
services:
  my-web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - my-postgres
    environment:
      DATABASE_URL: postgresql://postgres:a455328fm@my-postgres:5432/assignment
  my-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      # this setup will also represent in ./config/config.json
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a455328fm
      POSTGRES_DB: assignment
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - default
